# Generated by Django 4.2 on 2023-05-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50, verbose_name='Название актива')),
                ('asset_serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('asset_description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=50, verbose_name='Место расположения')),
                ('date_purchased', models.DateField(verbose_name='Дата приобретения')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата ремонта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата технического обслуживания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.asset')),
            ],
        ),
    ]
