# Generated by Django 4.2 on 2023-05-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_asset_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10, verbose_name='Стоимость актива'),
        ),
    ]
