# Generated by Django 4.2 on 2023-05-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_asset_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cost',
            field=models.CharField(default='0 руб.', max_length=50, verbose_name='Стоимость актива'),
        ),
    ]
